### ISSUE TITLE
Loading in html from file

### ISSUE THREAD

**Issue by mooror** [scotteh/php-dom-wrapper#1]
In your example I noticed you used '$doc->html($html);' to load in html from a variable. But I was wondering if you have a built in function for loading in html from a file instead? If not what do you propose I use?

**Comment by scotteh** [comment]
Not currently, you can read the file into a variable using file_get_contents() and pass it to the html method to achieve what you're after.

**Comment by mooror** [comment]
Thank you sir for your reply. You code worked very well. Cheers!
