### ISSUE TITLE
Partial HTML?

### ISSUE THREAD

**Issue by blueridgemountains1** [scotteh/php-dom-wrapper#14]
I'm running a partial html on it. How do I prevent it from wrapping it inside of doctype/html/body tags?

**Comment by scotteh** [comment]
The following may now work for you with v1.0.9.

``` php
$doc = new Document();
$doc->setLibxmlOptions(LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
```

You can find a full list of options available at: http://php.net/manual/en/libxml.constants.php
