### ISSUE TITLE
Fatal Error - Interrupting execution

### ISSUE THREAD

**Issue by BurakBoz** [scotteh/php-dom-wrapper#20]
Hi Im getting this error. I don't know this is a library error or mine but I think it's library related.
I'm using try catch blocks but it's still interrupts execution.
Any ideas why?

Composer.json require line: "scotteh/php-dom-wrapper": "^1.1",

> PHP Fatal error:  Uncaught Error: Call to a member function contents() on null in /Applications/MAMP/htdocs/grawler/vendor/scotteh/php-dom-wrapper/src/Traits/ManipulationTrait.php:694
Stack trace:
#0 /Applications/MAMP/htdocs/grawler/vendor/scotteh/php-dom-wrapper/src/Traits/ManipulationTrait.php(723): DOMWrap\NodeList->getHtml()
#1 /Applications/MAMP/htdocs/grawler/inc/Grawler/Site.php(142): DOMWrap\NodeList->html()
#2 /Applications/MAMP/htdocs/grawler/inc/Grawler/Site.php(278): Site->singlePost('http://www.kadi...')
#3 /Applications/MAMP/htdocs/grawler/vendor/scotteh/php-dom-wrapper/src/NodeList.php(161): Site->{closure}(Object(DOMWrap\Element))
#4 /Applications/MAMP/htdocs/grawler/inc/Grawler/Site.php(279): DOMWrap\NodeList->map(Object(Closure))
#5 /Applications/MAMP/htdocs/grawler/grawler.php(34): Site->pagination()
#6 {main}
  thrown in /Applications/MAMP/htdocs/grawler/vendor/scotteh/php-dom-wrapper/src/Traits/ManipulationTrait.php on line 694

Shorted code:

> private function xPathOrCss($exp)
{
    return (($exp{0} == "/" or $exp{0} == "(")? "findXPath" : "find");
}
public function pagination()
{
    try
    {
        $this->post->setSourceUrl($url);
        $raw = $this->curl->get($this->post->getSourceUrl());
        if ($this->curl->error or empty($raw) or $raw == false)
        {
            msg_error("Socket error on " . __CLASS__ . "/" . __METHOD__ . "():" . __LINE__ . " {$this->post->getSourceUrl()} with code {$this->curl->errorCode} and '{$this->curl->errorMessage}' message");
            return false;
        }
        $doc = new Document();
        $doc->html($raw);
        $content         = "";
        $contentSelector = conf("selectors", "selector_content");
        if (!empty($contentSelector))
        {
            $contentSelector = $doc->{$this->xPathOrCss($contentSelector)}($contentSelector);
 LINE 142:           if (!is_null($contentSelector) and method_exists($contentSelector, "html") and !empty($contentSelector->html())) $content = $contentSelector->html();
        }
        $this->post->setContent($content);
        unset($content);
    }
    catch (Exception $e)
    {
        msg_error("Single Post Exception : " . $e->getMessage());
    }
}

**Comment by BurakBoz** [comment]
**I've made an ugly change in "ManipulationTrait.php:694" and seems ok to me. at least I don't get fatal error and interruption now.**  


  public function getHtml(): string {
        $result = $this->collection();
        if(method_exists($result, "first")) $result = $result->first(); else return "";
        if(method_exists($result, "contents")) $result = $result->contents(); else return "";
        if(method_exists($result, "reduce")) $result = $result->reduce(function($carry, $node) {
            return $carry . $this->document()->saveHTML($node);
        }, ''); else return "";
        return $result;
    }

**Comment by scotteh** [comment]
Could you provide a document along with code to recreate the error?

**Comment by BurakBoz** [comment]
Sorry I don't know which document or which url causing this error. But it's obvious you chaining methods without controlling them. You should check before calling a method is it really a method or callable or null result? If one of them returns null everything else will mess up.
