### ISSUE TITLE
It required PHP 8.0.2

### ISSUE THREAD

**Issue by AdelDima** [scotteh/php-dom-wrapper#47]
I tested it today for my WordPress project and I find that this lib uses symfony/css-selector which required PHP 8.1  https://github.com/symfony/css-selector/blob/0dd5e36b80e1de97f8f74ed7023ac2b837a36443/composer.json

**Comment by scotteh** [comment]
It will work with css selector 4.x  (php 7.1.3) or 5.x (php 7.2.5).

**Comment by AdelDima** [comment]
Thanks, that what I did downgrade to 5
