### ISSUE TITLE
Fatal error: with DOMDocument::prepend(...$nodes): void in

### ISSUE THREAD

**Issue by h-agharezaei** [scotteh/php-dom-wrapper#50]
Hi, 
I have a following errors,
`Fatal error: Declaration of DOMWrap\Traits\ManipulationTrait::prepend($input): DOMWrap\Document must be compatible with DOMDocument::prepend(...$nodes): void in /var/www/.../admin/src/dist/php/Dom/vendor/scotteh/php-dom-wrapper/src/Traits/ManipulationTrait.php on line 276`

**Comment by scotteh** [comment]
You will need to use v2.x with PHP 8.
